# Automated Financial Program Configuration

# Server configuration
server:
  host: 127.0.0.1
  port: 5000
  workers: 4

# Development mode
development_mode: false

# Database configuration
database:
  type: sqlite  # sqlite, postgresql
  sqlite:
    path: data/financial_data.db
  postgresql:
    host: localhost
    port: 5432
    database: financial_app
    username: postgres
    password: postgres

# Ollama configuration
ollama:
  host: http://localhost:11434
  model: mistral
  timeout: 60
  max_tokens: 1024

# Accounting settings
accounting:
  standards:
    default: GAAP  # GAAP or IFRS
  currency: USD
  fiscal_year_start: 01-01  # MM-DD
  date_format: %Y-%m-%d

# Financial analysis
financial_analysis:
  ratio_precision: 2
  default_periods: 3  # Number of periods to show in trend analysis
  threshold_alerts:
    liquidity_ratio: 1.5
    debt_to_equity: 2.0
    profit_margin: 0.05

# AI and prediction settings
ai:
  forecasting:
    default_method: arima  # arima, prophet, linear
    confidence_interval: 0.95
    forecast_periods: 4
  anomaly_detection:
    sensitivity: medium  # low, medium, high
    training_window: 12  # months

# API integrations
api:
  exchange_rates:
    provider: exchangeratesapi
    key: your_api_key_here
    update_frequency: daily
  market_data:
    provider: alphavantage
    key: your_api_key_here
    symbols: [AAPL, MSFT, GOOGL]

# Export options
exports:
  excel:
    template_dir: data/templates/excel
    default_sheet_names: [Summary, Data, Charts]
  pdf:
    template_dir: data/templates/pdf
    company_logo: static/img/logo.png
    font: Helvetica

# Logging configuration
logging:
  level: INFO  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: logs/financial_app.log
  max_size: 10MB
  backup_count: 5

# User interface
ui:
  theme: light  # light, dark
  dashboard:
    default_chart: line
    charts_per_page: 4
    refresh_interval: 300  # seconds
  tables:
    rows_per_page: 15
    enable_export: true
  date_picker:
    format: MM/DD/YYYY
    default_range: last_quarter